export interface SubscriptionPlan {
  id: string;
  name: string;
  frequency: number;
  interval: string;
  deliveries_per_interval: number;
  account_id: string;
  created_at: string;
  updated_at: string;
  trial_available: boolean;
  trial_duration_frequency: number;
  trial_duration_interval: string;
  durations: { interval: string; frequency: number }[];
  trial_coupon_campaign_id: string;
  can_select_day_pattern: boolean;
  product: {
    id: string;
    name: string;
    slug: string;
    status: string;
    kind: string;
    variant_attributes: null;
    content: { summary: string; description: string };
    metadata: null;
    extradata: null;
    created_at: string;
    updated_at: string;
    account_id: string;
    tags: string[];
    subscription_plan_id: string;
    owner_type: null;
    owner_id: null;
    collections: string[];
    category_path: string;
    category_id: string;
    variants: {
      id: string;
      product_id: string;
      position: number;
      sku: string;
      name: string;
      status: string;
      attribute_values: null;
      price_units: null;
      list_price_units: null;
      is_default: boolean;
      is_backorderable: boolean;
      properties: null;
      metadata: null;
      extradata: null;
      created_at: string;
      updated_at: string;
      account_id: string;
      tax_number: null;
      store_tax_code_id: null;
      description: null;
      gtin_code: null;
      availability_start: null;
      availability_end: null;
      selling_status: null;
      owner_type: null;
      owner_id: null;
      managed_by_staff_id: null;
      media: { id: string; kind: string; created_at: string; updated_at: string; url: string; file: { key: string } }[];
      property_sets: any[];
    }[];
    property_sets: any[];
  };
}